server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///${user.home}/config-repo

#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/zhangxd1989/spring-boot-cloud
#          search-paths: config-repo

#security:
#  user:
#    name: user
#    password: ${CONFIG_SERVER_PASSWORD:password}
